### ISSUE TITLE
How to train GFLv2 on RetinaNet?

### ISSUE THREAD

**Issue by Zzh-tju** [implus/GFocalV2#3]
如题

**Comment by liushuai839** [comment]
你好,我在工程中并没有到GFLv2相应的代码.想问下你找到了吗?

**Comment by implus** [comment]
> 你好,我在工程中并没有到GFLv2相应的代码.想问下你找到了吗?

https://github.com/implus/GFocalV2/blob/master/mmdet/models/dense_heads/gfocal_head.py

**Comment by implus** [comment]
根据ATSS论文，RetinaNet和FCOS最大的区别不在于anchor，而在于正负样本的assign规则。所以我们实际上采用了1个anchor的RetinaNet，加上GFLV2的head进行训练的~

**Comment by Zzh-tju** [comment]
@implus 可是RetinaNet回归的是xywh呀

**Comment by implus** [comment]
> @implus 可是RetinaNet回归的是xywh呀

一样的，ATSS里面验证了xyhw和lrtb没有区别啊，所以用lrtb就可以了~

**Comment by Zzh-tju** [comment]
@implus 不对，你误解我的意思了

我是说RetinaNet回归的是xywh的偏移量，而tblr针对的是采样点到GT四条边的距离，后者可以用0～16的离散形式来预测，而前者呢？如果把RetinaNet也改成预测tblr，那不就变成了FCOS？

**Comment by implus** [comment]
ATSS论文的结论是：如何确定正负样本才是造成FCOS和RetinaNet效果差异的原因；

也就是说，两者最为本质的区别是如何assign正负样本，RetinaNet换成tblr，和FCOS还是有本质的区别的。

**Comment by Zzh-tju** [comment]
所以你指的是FCOS，但用的RetinaNet的正负样本定义方式？虽然正负样本是本质差别，而公认的RetinaNet是基于anchor的算法，回归的也是xywh的偏移量，难免会引起歧义。

**Comment by implus** [comment]
当然，xywh应该也可以进行缩放后用多个bin来预测，不过还没有尝试，大概率也是可以的蛤

**Comment by implus** [comment]
> 所以你指的是FCOS，但用的RetinaNet的正负样本定义方式？虽然正负样本是本质差别，而公认的RetinaNet是基于anchor的算法，回归的也是xywh的偏移量，难免会引起歧义。

嗯，了解，我会在后续更新版把这里说明一下蛤，其实早期版本有注释说明，好像当时是因为页数的原因拿掉了~

**Comment by implus** [comment]
> > 所以你指的是FCOS，但用的RetinaNet的正负样本定义方式？虽然正负样本是本质差别，而公认的RetinaNet是基于anchor的算法，回归的也是xywh的偏移量，难免会引起歧义。
> 
> 嗯，了解，我会在后续更新版把这里说明一下蛤，其实早期版本有注释说明，好像当时是因为页数的原因拿掉了~

感谢指正！~

**Comment by Zzh-tju** [comment]
还有关于知乎上提到的，`GFLV2也是检测历史上第一个用学习到的分布的统计特征去指导质量估计的`。对此是不是忽略了gaussianYOLO，它用学习到的gauss分布来惩罚了分类得分。

**Comment by implus** [comment]
嗯，这个的确有点相关，后续我加到discussion里面。不过gaussianYOLO那会还没有明确的端到端学习定位质量估计（和分类联合分布）的概念，同时也没有更好的一般化分布的概念，所以还是有一些区别的。感谢指正~~
