### ISSUE TITLE
training custom dataset

### ISSUE THREAD

**Issue by Jack-Hu-2001** [implus/GFocalV2#30]
I have finished writing a brief Chinese blog and introduced the problems I faced in installing and training. I would like to share it so that before the install.md and other guidelines are released, other Chinese students can view it as a substitue.
link: https://blog.csdn.net/JackHu12345/article/details/119881093
Hope I can offer some help!
As for why I didn't write an English version, well , my English is poor. 
I'll update my blog if more question is arosen when I'm available.

**Comment by implus** [comment]
Thanks a lot for your sincere effort~~

**Comment by Jack-Hu-2001** [comment]
现在有非常棒的install指导啦，俺就先把这个issue关了不献丑啦
